CC=gcc
CFLAGS=-DLIQUIDITY_PROVIDER=1 -O2 -I/usr/lib/x86_64-linux-gnu/curl

%.o:%.c
	$(CC) $(CFLAGS) -c -o $@ $^

all: libjpeg.a

libjpeg.a: unix/jmemname.o \
		jaricom.o \
		jcapimin.o \
		jcapistd.o \
		jcarith.o \
		jccoefct.o \
		jccolor.o \
		jcdctmgr.o \
		jchuff.o \
		jcinit.o \
		jcmainct.o \
		jcmarker.o \
		jcmaster.o \
		jcomapi.o \
		jcparam.o \
		jcprepct.o \
		jcsample.o \
		jctrans.o \
		jdapimin.o \
		jdapistd.o \
		jdarith.o \
		jdatadst.o \
		jdatasrc.o \
		jdcoefct.o \
		jdcolor.o \
		jddctmgr.o \
		jdhuff.o \
		jdinput.o \
		jdmainct.o \
		jdmarker.o \
		jdmaster.o \
		jdmerge.o \
		jdpostct.o \
		jdsample.o \
		jdtrans.o \
		jerror.o \
		jfdctflt.o \
		jfdctfst.o \
		jfdctint.o \
		jidctflt.o \
		jidctfst.o \
		jidctint.o \
		jmemmgr.o \
		jquant1.o \
		jquant2.o \
		jutils.o
	$(AR) -r libjpeg.a $^

clean:
	$(RM) *.o
	$(RM) libjpeg.a
