#!/bin/bash

# add KMD 
coins/kmd_7776

# Unlock wallet. 
./wp_7776

# external coins.
coins/ltc_7776

# Loop through assetchains.json and build the path to the appropriate coins file and run it.
./listassetchains | while read chain; do
    coin="coins/$(echo $chain | awk '{print tolower($0)}')_7776"
    $coin
done

# old version of dual coins.
coins/gleecold_7776
