#!/bin/bash
set -x
source pubkey.txt
echo $pubkey
sleep 3

# add non default assetchains here.

# Loop through assetchains.json and call dpow for them. ROFX will not add a second time.
./listassetchains | while read chain; do
    curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"$chain\",\"pubkey\":\"$pubkey\"}"
done
