#!/usr/bin/env python3
import os
import json

def format_param(param, value):
    return '-' + param + '=' + value

script_dir = os.path.dirname(__file__)
with open(script_dir + '/assetchains.json') as file:
    assetchains = json.load(file)

for chain in assetchains:
    params = []
    for param, value in chain.items():
        if isinstance(value, list):
            for dupe_value in value:
                params.append(format_param(param, dupe_value))
        else:
            if param == 'datadir' and '${HOME}' in value:
                home_dir = os.environ['HOME']
                value = value.replace('${HOME}', home_dir)
            params.append(format_param(param, value))
    print(' '.join(params))
