#!/bin/bash
# manually kill the iguana you need to restart first!

# unlock any locked utxos. This will unlock utxos for both iguans, need a filter for address to only unlock the pubkey you need to restart. 
komodo-cli lockunspent true `komodo-cli listlockunspent | jq -c .` 

# Start normally, no split is default on this branch. 
stdbuf -oL $1 ../agents/iguana notary & #> iguana.log 2> error.log  &

myip=`curl -s4 checkip.amazonaws.com`
source pubkey.txt

sleep 4
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"SuperNET\",\"method\":\"myipaddr\",\"ipaddr\":\"$myip\"}"
sleep 3

# Season 8 Main peers
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"addnotary\",\"ipaddr\":\"15.235.204.174\"}" # Dragonhound_AR
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"addnotary\",\"ipaddr\":\"209.222.101.247\"}" # Dragonhound_NA
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"addnotary\",\"ipaddr\":\"178.159.2.9\"}" # Dragonhound_EU
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"addnotary\",\"ipaddr\":\"51.161.198.87\"}" # Dragonhound_SH
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"addnotary\",\"ipaddr\":\"103.195.100.32\"}" # Dragonhound_DEV
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"addnotary\",\"ipaddr\":\"141.94.195.209\"}" # QA_DEV
curl --url "http://127.0.0.1:7779" --data "{\"agent\":\"iguana\",\"method\":\"addnotary\",\"ipaddr\":\"148.113.1.52\"}" # gcharang_AR
curl --url "http://127.0.0.1:7779" --data "{\"agent\":\"iguana\",\"method\":\"addnotary\",\"ipaddr\":\"51.161.209.100\"}" # gcharang_SH
curl --url "http://127.0.0.1:7779" --data "{\"agent\":\"iguana\",\"method\":\"addnotary\",\"ipaddr\":\"51.161.172.84\"}" # gcharang_SH2
curl --url "http://127.0.0.1:7779" --data "{\"agent\":\"iguana\",\"method\":\"addnotary\",\"ipaddr\":\"148.113.8.6\"}" # gcharang_DEV
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"addnotary\",\"ipaddr\":\"178.159.2.6\"}" # blackice_eu
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"addnotary\",\"ipaddr\":\"51.79.18.36\"}" # blackice_na


# add coins
./add_coins

sleep 30

# dpow for KMD->LTC.
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"KMD\",\"pubkey\":\"$pubkey\"}"

sleep 20

# dpow for ACs
./dpowassets
